# Generated by Django 4.0.3 on 2022-03-29 07:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LiveMessages',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('create_dt', models.DateTimeField(auto_now_add=True, help_text='When was the background task started?')),
                ('message', models.CharField(help_text='Text displayed as live feedback to the user', max_length=200)),
                ('result', models.CharField(choices=[('error', 'error'), ('success', 'success'), ('unknown', 'unknown')], default='unknown', help_text='Status of the task', max_length=7)),
                ('completed', models.BooleanField(default=False, help_text='Is this "background task" finished?')),
                ('acknowledged', models.BooleanField(default=False, help_text='User would like to hide this messages')),
                ('user', models.ForeignKey(help_text='Which user started the the background task?', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
